name: zarn-sast
description: A lightweight static security analysis tool for modern Perl Apps
author: Heitor Gouvêa
branding:
  icon: "shield"
  color: "blue"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        SOURCE: ${{ inputs.source }}
        RULES: ${{ inputs.rules }}
        IGNORE: ${{ inputs.ignore }}
        SARIF: ${{ inputs.sarif }}
      run: |
        docker run ghcr.io/htrgouvea/zarn/zarn:latest \
          --source ${SOURCE:-''} \
          --rules ${RULES:-''} \
          --ignore ${IGNORE:-''} \
          --sarif ${SARIF:-''}
