---
rules:
  - id: '0001'
    category: info
    name: Debug module enabled
    message:
    sample:
      - Dumper
      # - Devel::Graph
      # - Devel::StackTrace
  - id: '0002'
    category: vuln
    name: Remote Command Execution // Code Injection
    message: 
    sample:
      - system
      - eval
      - exec
  - id: '0003'
    category: vuln
    name: Path Traversal
    message: 
    sample:
      - open
  - id: '0004'
    category: warn
    name: Timing Attack
    message: 
    sample:
      - ==
  - id: '0005'
    category: vuln
    name: Weak Criptography Algorithm
    message: 
    sample:
      - md5
  # - id: '0006'
  #   category: vuln
  #   name: Hard-coded Credentials
  #   message:
  #   sample:
  #     - password