---
rules:
  - id: '0001'
    category: info
    name: Debug module enabled
    message:
    sample:
      - Dumper
  - id: '0002'
    category: vuln
    name: Code Injection
    message: 
    sample:
      - system
      - eval
      - exec
  - id: '0003'
    category: vuln
    name: Path Traversal
    message: 
    sample:
      - open
  - id: '0004'
    category: warn
    name: Timing Attack
    message: 
    sample:
      - ==
  - id: '0005'
    category: vuln
    name: Weak Hash Algorithm
    message: 
    sample:
      - md5


# Generic notes
# CPAN Protocol: cpan://https://metacpan.org/pod/LWP#CPAN-Requests
# Strict/warnings for modules: https://metacpan.org/pod/Carp