name: Linter / Perl Critic

on:
  pull_request:
    branches:
      - main

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - name: Perl Critic
      uses: Difegue/action-perlcritic@master
      with:
          args: ./lib/*