name: Linter / Perl Critic

on:
  pull_request:
    branches:
      - main

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - name: perlcritic
      uses: gugod/actions-perlcritic@v1.0
      with:
        paths: "."
        options: "-p .perlcriticrc"